export const TIME_FORMAT_HOURS = "HOURS";
export const TIME_FORMAT_MINUTES = "MINUTES";
export const TIME_FORMAT_MONEY = "MONEY";

export const DATE_FORMAT_DATE = "DATE";
export const DATE_FORMAT_MONTH = "MONTH";

export const RESULT_GROUP_NONE = "NONE";
export const RESULT_GROUP_WORKER = "WORKER";
export const RESULT_GROUP_QUEUE = "QUEUE"; // Группировка по очереди
export const RESULT_GROUP_PROJECT = "PROJECT";
export const RESULT_GROUP_EPIC = "EPIC"; // Группировка по эпику
export const RESULT_GROUP_ISSUE = "ISSUE"; // Группировка по задаче
export const RESULT_GROUP_ISSUE_TYPE = "ISSUE_TYPE"; // Группировка по типу задачи

export const DEPTH_COLORS = [
    'rgba(0, 0, 255, 0.12)',
    'rgba(0, 0, 255, 0.18)',
    'rgba(0, 0, 255, 0.24)',
    'rgba(0, 0, 255, 0.30)',
    'rgba(0, 0, 255, 0.36)',
    'rgba(0, 0, 255, 0.42)'
];

export const RESULT_GROUPS_TRANSLATIONS = {
    [RESULT_GROUP_NONE]: "Нет",
    [RESULT_GROUP_ISSUE]: "Задача",
    [RESULT_GROUP_WORKER]: "Автор",
    [RESULT_GROUP_EPIC]: "Эпик",
    [RESULT_GROUP_QUEUE]: "Очередь",
    [RESULT_GROUP_PROJECT]: "Проект",
    [RESULT_GROUP_ISSUE_TYPE]: "Тип задачи"
};

export const RESULT_GROUPS = [
    [ RESULT_GROUP_ISSUE, RESULT_GROUP_WORKER, RESULT_GROUP_QUEUE, RESULT_GROUP_PROJECT, RESULT_GROUP_ISSUE_TYPE, RESULT_GROUP_EPIC ],
    [ RESULT_GROUP_NONE, RESULT_GROUP_ISSUE, RESULT_GROUP_WORKER, RESULT_GROUP_QUEUE, RESULT_GROUP_PROJECT, RESULT_GROUP_ISSUE_TYPE, RESULT_GROUP_EPIC ],
    [ RESULT_GROUP_NONE, RESULT_GROUP_ISSUE, RESULT_GROUP_WORKER, RESULT_GROUP_QUEUE, RESULT_GROUP_PROJECT, RESULT_GROUP_ISSUE_TYPE, RESULT_GROUP_EPIC ],
    [ RESULT_GROUP_NONE, RESULT_GROUP_ISSUE, RESULT_GROUP_WORKER, RESULT_GROUP_QUEUE, RESULT_GROUP_PROJECT, RESULT_GROUP_ISSUE_TYPE, RESULT_GROUP_EPIC ],
    [ RESULT_GROUP_NONE, RESULT_GROUP_ISSUE, RESULT_GROUP_WORKER, RESULT_GROUP_QUEUE, RESULT_GROUP_PROJECT, RESULT_GROUP_ISSUE_TYPE, RESULT_GROUP_EPIC ],
    [ RESULT_GROUP_NONE, RESULT_GROUP_ISSUE, RESULT_GROUP_WORKER, RESULT_GROUP_QUEUE, RESULT_GROUP_PROJECT, RESULT_GROUP_ISSUE_TYPE, RESULT_GROUP_EPIC ],
];

export const DATE_FORMAT = "DD.MM.YYYY";

export const WEEKEND_WEEK_DAYS = [6, 7];

export const CREATE_WORK_LOG_FORM_TYPE_BASIC = "BASIC";
export const CREATE_WORK_LOG_FORM_TYPE_ADVANCED = "ADVANCED";

export const TASK_SEARCH_TYPE_BASE = "BASE";
export const TASK_SEARCH_TYPE_BOARD = "BOARD";

export const AUTHORIZED_STATE_DONE = "DONE";
export const AUTHORIZED_STATE_NONE = "NONE";
export const AUTHORIZED_STATE_NO_ORG_ID = "NO_ORG_ID";

export const EXPORT_VARIANT_AS_IS = "AS_IS";
export const EXPORT_VARIANT_ONE_ROW = "ONE_ROW";
export const EXPORT_VARIANT_ONE_ROW_WITH_DATE = "ONE_ROW_WITH_DATE";
export const EXPORT_VARIANT_SHORT = "SHORT";